### ISSUE TITLE
Inside of CT10 nozzle has sharp edges (should be smooth)

### ISSUE THREAD

**Issue by blowfishpro** [ChrisAdderley/CryoEngines#2]
Visible when the part is highlighted (and to a lesser extend the rest of the time).  All the other engines have smooth shading on those edges.

**Comment by ChrisAdderley** [comment]
Fixed in https://github.com/ChrisAdderley/CryoEngines/commit/08bdc4660751fb987c37e47034c0893158d31658, will be in next release.
