### ISSUE TITLE
Missing IntakeAir ratio change in the MkIVSystem patch

### ISSUE THREAD

**Issue by Xaryen** [ChrisAdderley/CryoEngines#21]
Noticed somebody posted this in the MkIV thread so doublechecked and there is indeed a missing @PROPELLANT[IntakeAir] in the CutlassLH2.cfg patch so the game keeps using the 1 : 6 ratio for LF/Air, which leads to rather extreme IntakeAir requirements.
Per my math, considering  the fuel/oxidizer fraction changed from 0.82 to 15 (multiplied by 18.29) when converting LF/O->LH2/O for closed cycle. With a 1.0 fraction for LH2 in Airbreathing mode, the new IntakeAir fraction should be 0.328 for a 1 : 0.328 ratio.

**Comment by ChrisAdderley** [comment]
As I mentioned... somewhere.... it's fixed in my local version. I will push it to dev to show you...

**Comment by ChrisAdderley** [comment]
Note that it won't be released until post KSP 1.3.

**Comment by Xaryen** [comment]
Oh many apologies then, I checked both CryoE and MkIV threads and dev branches but wasn't able to find anything. I already fixed it locally just wasn't confident enough to post a Pull req. in case something was wrong.

**Comment by ChrisAdderley** [comment]
No worries. I couldn't fine the post that said I fixed it so maybe I hallucinated posting that. It happens to me sometimes.
