### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Stratickus** [ChrisAdderley/CryoEngines#22]
Feature Request: Ability to Enable/Disable Cooling for Cryo tanks in VAB/Editor. 

Would allow for minimizing EC drain for 1st stage tanks where boiloff is usually not a concern. This would be beneficial as it would persist across saved craft files. As it stands it must be done prior to launch or inflight.

Cheers,

**Comment by ChrisAdderley** [comment]
This... should already be a thing.

**Comment by ChrisAdderley** [comment]
Resolved
