### ISSUE TITLE
Part Request - 0.625m Cryo Engine Part

### ISSUE THREAD

**Issue by GHrynk** [ChrisAdderley/CryoEngines#40]
Requesting addition of a 0.625m LH2/Ox engine in the 20-30kN (vac) class, similar to NV-10 Eel, to complement the Volcano at tech level 4.  Target application is landers for airless moons, so extensible nozzle for maximal ISP not required.

**Comment by ChrisAdderley** [comment]
I'll leave this open because I might do it in the future but probably not anytime soon.

**Comment by ChrisAdderley** [comment]
Coming in 1.0.0, or, something similar at least.
