### ISSUE TITLE
Engine light config fix

### ISSUE THREAD

**Issue by Nightside101010** [ChrisAdderley/CryoEngines#46]

**Comment by Nightside101010** [comment]
It looks like the name of the Engine Light module was changed along with the... I don't know what the things inside the module are called... Anyway I just updated the Engine light to the current config and it looks great, but if you are interested I think the mod provides some more things to play with than it used to.

`// Tweaks the colour of the EngineLight lights

@PART[cryoengine-125-1]:AFTER[EngineLight]
{
	@MODULE[EngineLightEffect]
    { 
		%engineEmissiveMultiplier = 1.0
		%lightPower = 1.0
		%lightRange = 40.0
		%maxLightPower = 23.0
		%exhaustRed = 1
		%exhaustGreen = 0.88
		%exhaustBlue = 0.68
	}
}
@PART[cryoengine-125-2]:AFTER[EngineLight]
{
	@MODULE[EngineLightEffect]
    { 
		%engineEmissiveMultiplier = 1.0
		%lightPower = 1.0
		%lightRange = 40.0
		%maxLightPower = 23.0
		%exhaustRed = 1
		%exhaustGreen = 0.4
		%exhaustBlue = 0.3
	}
}
@PART[cryoengine-25-1]:AFTER[EngineLight]
{
	
}
@PART[cryoengine-25-2]:AFTER[EngineLight]
{
	@MODULE[EngineLightEffect]
    { 
		%lightPower = 1.0
		%lightRange = 40.0
		%maxLightPower = 23.0
		%exhaustRed = 1
		%exhaustGreen = 0.4
		%exhaustBlue = 0.3
	}
}
@PART[cryoEngine-375-1]:AFTER[EngineLight]
{
	
}
@PART[cryoengine-375-2]:AFTER[EngineLight]
{
	@MODULE[EngineLightEffect]
    { 
		%lightPower = 1.0
		%lightRange = 40.0
		%maxLightPower = 23.0
		%exhaustRed = 1
		%exhaustGreen = 0.4
		%exhaustBlue = 0.3
	}
}`

**Comment by ChrisAdderley** [comment]
It'd be great if you could submit this as a PR!

**Comment by Nightside101010** [comment]
Sure! I want to test it with all the engines first, I was only using the KS-68.
