### ISSUE TITLE
Localisation string for Disabling Cooling on tanks has typo

### ISSUE THREAD

**Issue by deimos790** [ChrisAdderley/CryoEngines#56]
from en-us.cfg:
There should be an "=" before "Disable Cooling" not a minus sign. 

    #LOC_CryoTanks_ModuleCryoTank_Action_EnableAction = Enable Cooling
    #LOC_CryoTanks_ModuleCryoTank_Action_DisableAction - Disable Cooling
    #LOC_CryoTanks_ModuleCryoTank_Action_ToggleAction = Toggle Cooling

**Comment by ChrisAdderley** [comment]
Resolve in CryoTanks 1.2.0
