### ISSUE TITLE
CE-10 - some sort of nonexistent mesh is highlighted

### ISSUE THREAD

**Issue by blowfishpro** [ChrisAdderley/CryoEngines#62]
![image](https://user-images.githubusercontent.com/10545461/62018644-6a563980-b170-11e9-98c8-e748988daed5.png)

**Comment by blowfishpro** [comment]
CE-60 seems to have it too

**Comment by ChrisAdderley** [comment]
hmm. Setting that to TransparentFX used to work to kill the highlight shader but not anymore.

**Comment by ChrisAdderley** [comment]
Fixed in 1.0.1
