### ISSUE TITLE
MFT causes accelerated LqdHydrogen burn at higher altitudes

### ISSUE THREAD

**Issue by leops1984** [ChrisAdderley/CryoEngines#9]
I've found some weird bug involving Modular Fuel Tanks and this mod. If MFT is installed, the LqdHydrogen burn rate increases (and excess Oxidizer is left) - but only at lower atmospheric pressures or vacuum conditions. If the engine is test-fired at ground level, the burn rate is normal.

I tested this bug by installing only Hyperedit, and CryoEngines on a stock KSP install. The test rocket burned LqdHydrogen fine at a 100km orbit. Add MFT and the burn rate goes out of whack.

**Comment by RealKolago** [comment]
Maybe you lose some LqdHydrogen because of boil off.

**Comment by ChrisAdderley** [comment]
This doesn't really make any sense. We do have some users using MFT with cryoengines with no problems. Any more information?

**Comment by leops1984** [comment]
Yeah, I understand it makes no sense, but that's what I found. My test procedure was basically this:

1. Add CryoEngines to a newly-downloaded stock install of KSP from Steam.
2. Construct a test craft - engine, tank, control pod, reaction wheel.
3. Test at ground level, verify that fuel burn is normal.
4. Test at 100km orbit (brought to that level by Hyperedit). LqdHydrogen burn rate is higher than it should be.

I can try putting a GIF together if it will help.

**Comment by ChrisAdderley** [comment]
A gif/video clip would help, but I can't think of any behaviour that I've created that would cause this.
